option(ENGINE_ASAN "Enable AddressSanitizer + LeakSanitizer" OFF)
option(ENGINE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(ENGINE_TSAN "Enable ThreadSanitizer" OFF)

function(engine_enable_sanitizers target_name)
  if(ENGINE_TSAN AND (ENGINE_ASAN OR ENGINE_UBSAN))
    message(FATAL_ERROR "ThreadSanitizer cannot be combined with ASan/UBSan in one binary")
  endif()

  set(SANITIZE_FLAGS "")
  if(ENGINE_ASAN)
    list(APPEND SANITIZE_FLAGS -fsanitize=address -fsanitize=leak)
  endif()
  if(ENGINE_UBSAN)
    list(APPEND SANITIZE_FLAGS -fsanitize=undefined)
  endif()
  if(ENGINE_TSAN)
    list(APPEND SANITIZE_FLAGS -fsanitize=thread)
  endif()

  if(SANITIZE_FLAGS)
    target_compile_options(${target_name} INTERFACE ${SANITIZE_FLAGS} -fno-omit-frame-pointer -g)
    target_link_options(${target_name} INTERFACE ${SANITIZE_FLAGS})
  endif()
endfunction()
